baseurl = "http://www.example.com"
title = "Mr. EmPee"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Manuel P."
  info = "Java Backend Developer"
  description = "Mr. EmPee's personal website"
  keywords = "blog,developer,personal,minecraft,mod,plugin"
  avatarurl = "images/logo.png"

  favicon_32 = "images/favicon.ico"
  favicon_16 = "images/favicon.ico"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Mr-EmPee"
[[params.social]]
  name = "Spigot"
  icon = "fa fa-gg fa-2x"
  weight = 2
  url = "https://www.spigotmc.org/resources/authors/empee.644439/"
[[params.social]]
  name = "Discord"
  icon = "fa fa-discord-alt fa-2x"
  weight = 2
  url = "https://discord.com/invite/XBxqAtasS5"
[[params.social]]
  name = "Sponsor"
  icon = "fa fa-coffee fa-2x"
  weight = 2
  url = "https://ko-fi.com/empee"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"